### ISSUE TITLE
Filename variable is empty and not correctly used

### ISSUE THREAD

**Issue by FabianTe** [VisualAppeal/PHP-Auto-Update#54] opened 2021-09-15 15:21 UTC
Hi,

while debugging I noticed, that in [this piece of code](https://github.com/VisualAppeal/PHP-Auto-Update/blob/master/src/AutoUpdate.php#L806-L813) the `filename` variable seems to have issue:

![image](https://user-images.githubusercontent.com/7669818/133460230-90cbe27e-1320-4732-9da8-3cf942ed4a14.png)

The variable `filename` is always `""` even though in `fileStats` there is a valid name.

I am not sure but this seems strange to me. Is this intended behaviour?

**Comment by thelfensdrfer** [comment] 2021-09-16 17:11
According to https://www.php.net/manual/en/ziparchive.statindex.php `statIndex` returns an array with a `name` key. That's what get stored in `$filename`. Of course under special circumstances this can be empty I suspect, e.g. when extracting the root directory.

**Comment by thelfensdrfer** [comment] 2021-09-16 17:21
Sorry, wrong line. You are completely right and this issue is in fact a duplicate of #51. But this should be fixed now. I find it very hard to create tests for the whole zip extraction process, so if you have any idea or motivation, please feel free to provide some.

**Closed by thelfensdrfer** 2021-09-16 17:21 UTC
Labels: bug
